server:
  port: 8080
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bzy_route
          uri: http://www.standard.jinzhicloud.com
          predicates:
            - Path=/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/


logging:
  level:
    org.springframework.cloud.gateway: debug