server:
    port: 8081
spring:
    application:
        name: spring-cloud-producer

eureka:
    client:
        service-url:
            defaultZone: http://127.0.0.1:8000/eureka
        register-with-eureka: true
        fetch-registry: true
