server:
    port: 8086
spring:
    application:
        name: seata-storage-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/seat-storage?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 123456
eureka:
    client:
        service-url:
            defaultZone: http://127.0.0.1:8000/eureka
        register-with-eureka: true
        fetch-registry: true
